<?php
/**
 * CSRF Protection Helper
 *
 * Generates and validates CSRF tokens to protect POST forms
 * from Cross-Site Request Forgery attacks.
 *
 * How it works:
 * 1. generateCsrfToken() creates a random token and stores it in the session.
 * 2. Add <?= csrfField() ?> inside your <form> tag to output the token.
 * 3. On form submission, call validateCsrfToken($_POST['_csrf_token'] ?? '')
 *    to check the token matches.
 *
 * Dependencies:
 *   - includes/session.php (must be loaded before this file)
 *
 * PHP 8.3
 */

/**
 * Generate (or retrieve) a CSRF token stored in the session.
 *
 * @param bool $force  If TRUE, always generates a new token.
 * @return string  The 64-character hex token.
 */
function generateCsrfToken(bool $force = false): string
{
    if ($force || !isset($_SESSION['_csrf_token'])) {
        // 32 random bytes = 64 hex characters — cryptographically secure
        $_SESSION['_csrf_token'] = bin2hex(random_bytes(32));
    }

    return $_SESSION['_csrf_token'];
}

/**
 * Validate a submitted CSRF token against the session-stored token.
 *
 * @param string $submittedToken  The token from the form (_POST['_csrf_token']).
 * @return bool  TRUE if valid, FALSE otherwise.
 */
function validateCsrfToken(string $submittedToken): bool
{
    // If no token in session, the form was never generated by our server
    if (!isset($_SESSION['_csrf_token'])) {
        return false;
    }

    // hash_equals() prevents timing attacks by comparing in constant time
    return hash_equals($_SESSION['_csrf_token'], $submittedToken);
}

/**
 * Generate a complete hidden <input> field with the CSRF token.
 *
 * Usage inside <form>:
 *   <?= csrfField() ?>
 *
 * @return string  HTML markup for the hidden input.
 */
function csrfField(): string
{
    $token = generateCsrfToken();
    return '<input type="hidden" name="_csrf_token" value="' . $token . '">';
}
