[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:mariadbd]
command=/usr/sbin/mariadbd --user=mysql --bind-address=127.0.0.1 --port=3306 --innodb-buffer-pool-size=48M --performance-schema=OFF --skip-name-resolve
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:apache]
command=/usr/sbin/apache2 -DFOREGROUND
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0