<?php
/**
 * Security Utility Functions
 *
 * Input sanitization, CSRF token generation, and CSRF validation.
 *
 * Why this file exists:
 * - sanitize() prevents XSS attacks by escaping HTML special characters.
 * - CSRF tokens protect your forms from Cross-Site Request Forgery attacks.
 *
 * How CSRF protection works:
 * 1. When a form is displayed, generateCSRFToken() creates a random token
 *    and stores it in the session.
 * 2. The same token is added as a hidden field in the form.
 * 3. When the form is submitted, validateCSRFToken() checks that the
 *    submitted token matches the one in the session.
 * 4. If they don't match, the request is rejected (someone tried to forge it).
 *
 * Dependencies:
 *   - includes/session.php (for $_SESSION access)
 *
 * PHP 8.3
 */

// ─── Input Sanitization ────────────────────────────────────────────────

/**
 * Cleans a string for safe output in HTML.
 *
 * What it does:
 * - Trims whitespace from the beginning and end.
 * - Converts special HTML characters (&, <, >, ", ') to their HTML entities.
 * - This prevents malicious HTML or JavaScript from being injected.
 *
 * @param string $data  The raw input string.
 *
 * @return string  The sanitized string, safe to output in HTML.
 */
function sanitize(string $data): string
{
    return htmlspecialchars(trim($data), ENT_QUOTES, 'UTF-8');
}

// ─── CSRF Token Generation ─────────────────────────────────────────────

if (!function_exists('generateCSRFToken')) {
/**
 * Generates a new CSRF token and stores it in the session.
 *
 * If a token already exists, it reuses it (so the user's form doesn't
 * break if they refresh the page). To force a new token, use $force = true.
 *
 * @param bool $force  If TRUE, generates a new token even if one exists.
 *
 * @return string  The CSRF token value.
 */
function generateCSRFToken(bool $force = false): string
{
    if ($force || !isset($_SESSION['_csrf_token'])) {
        // Generate a random 32-byte token and convert to hexadecimal
        $_SESSION['_csrf_token'] = bin2hex(random_bytes(32));
    }

    return $_SESSION['_csrf_token'];
}
}

// ─── CSRF Token Validation ─────────────────────────────────────────────

if (!function_exists('validateCSRFToken')) {
/**
 * Validates a submitted CSRF token against the one stored in the session.
 *
 * How to use in a form:
 *   1. In your form HTML: <input type="hidden" name="_csrf_token"
 *      value="<?= generateCSRFToken() ?>">
 *   2. In your form handler: if (!validateCSRFToken($_POST['_csrf_token'] ?? '')) {
 *      // reject the request
 *      }
 *
 * @param string $submittedToken  The token from the submitted form.
 *
 * @return bool  TRUE if the token is valid, FALSE otherwise.
 */
function validateCSRFToken(string $submittedToken): bool
{
    // If no token exists in the session, the form wasn't generated by us
    if (!isset($_SESSION['_csrf_token'])) {
        return false;
    }

    $storedToken = $_SESSION['_csrf_token'];

    // Use hash_equals() instead of === to prevent timing attacks
    return hash_equals($storedToken, $submittedToken);
}
}

// ─── AJAX CSRF Validation ───────────────────────────────────────────────

/**
 * Validates CSRF token from an AJAX request header.
 *
 * Call this in AJAX handlers to check for the X-CSRF-Token header.
 *
 * Usage:
 *   $headers = getallheaders();
 *   if (!validateCSRFTokenRequest($headers['X-CSRF-Token'] ?? '')) {
 *       http_response_code(403);
 *       echo json_encode(['error' => 'Invalid security token']);
 *       exit;
 *   }
 *
 * @param string $fromRequest  Token from X-CSRF-Token header.
 *
 * @return bool  TRUE if valid.
 */
function validateCSRFTokenRequest(string $fromRequest = ''): bool
{
    if ($fromRequest === '') {
        $headers = getallheaders();
        $fromRequest = $headers['X-CSRF-Token'] ?? $headers['x-csrf-token'] ?? '';
    }
    return validateCSRFToken($fromRequest);
}

// ─── Security Headers ───────────────────────────────────────────────────

/**
 * Sends security-related HTTP headers to protect against common attacks.
 *
 * Call this at the top of any page (AFTER session start) to apply:
 *   - X-Content-Type-Options: nosniff
 *   - X-Frame-Options: DENY
 *   - Referrer-Policy: strict-origin-when-cross-origin
 *   - Permissions-Policy: restricted feature set
 *   - Content-Security-Policy (relaxed for Bootstrap CDN)
 *
 * @return void
 */
function addSecurityHeaders(): void
{
    // Prevent MIME-type sniffing
    header('X-Content-Type-Options: nosniff');

    // Prevent clickjacking
    header('X-Frame-Options: DENY');

    // Control referrer information
    header('Referrer-Policy: strict-origin-when-cross-origin');

    // Restrict browser features
    header("Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()");

    // Content Security Policy — relaxed enough for Bootstrap Icons CDN
    $csp = "default-src 'self'; "
         . "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; "
         . "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; "
         . "font-src 'self' https://cdn.jsdelivr.net; "
         . "img-src 'self' data:; "
         . "frame-ancestors 'none'; "
         . "form-action 'self'";
    header('Content-Security-Policy: ' . $csp);
}
